# Generated by Django 5.2.16 on 2026-07-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_system_prompt', models.TextField(default='You are AVC Bot, the official assistant of Amazing Voices Choir...')),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
