# Generated by Django 5.2.16 on 2026-07-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoirSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BASS', 'Bass'), ('TENOR', 'Tenor'), ('ALTO', 'Alto'), ('SOPRANO', 'Soprano')], max_length=10, unique=True)),
            ],
        ),
    ]
