/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SelectSectionRouteImport } from './routes/select-section'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDebtRouteImport } from './routes/_app.debt'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppMusicRouteImport } from './routes/_app.music'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStatisticsRouteImport } from './routes/_app.statistics'
import { Route as AppUploadsRouteImport } from './routes/_app.uploads'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSectionRoute = SelectSectionRouteImport.update({
  id: '/select-section',
  path: '/select-section',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtRoute = AppDebtRouteImport.update({
  id: '/debt',
  path: '/debt',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppMusicRoute = AppMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadsRoute = AppUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/select-section': typeof SelectSectionRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/debt': typeof AppDebtRoute
  '/documents': typeof AppDocumentsRoute
  '/members': typeof AppMembersRoute
  '/music': typeof AppMusicRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/statistics': typeof AppStatisticsRoute
  '/uploads': typeof AppUploadsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/select-section': typeof SelectSectionRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/debt': typeof AppDebtRoute
  '/documents': typeof AppDocumentsRoute
  '/members': typeof AppMembersRoute
  '/music': typeof AppMusicRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/statistics': typeof AppStatisticsRoute
  '/uploads': typeof AppUploadsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/select-section': typeof SelectSectionRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debt': typeof AppDebtRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/music': typeof AppMusicRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/statistics': typeof AppStatisticsRoute
  '/_app/uploads': typeof AppUploadsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/register'
    | '/select-section'
    | '/announcements'
    | '/approvals'
    | '/dashboard'
    | '/debt'
    | '/documents'
    | '/members'
    | '/music'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/statistics'
    | '/uploads'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending'
    | '/register'
    | '/select-section'
    | '/announcements'
    | '/approvals'
    | '/dashboard'
    | '/debt'
    | '/documents'
    | '/members'
    | '/music'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/statistics'
    | '/uploads'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pending'
    | '/register'
    | '/select-section'
    | '/_app/announcements'
    | '/_app/approvals'
    | '/_app/dashboard'
    | '/_app/debt'
    | '/_app/documents'
    | '/_app/members'
    | '/_app/music'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/statistics'
    | '/_app/uploads'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
  SelectSectionRoute: typeof SelectSectionRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-section': {
      id: '/select-section'
      path: '/select-section'
      fullPath: '/select-section'
      preLoaderRoute: typeof SelectSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debt': {
      id: '/_app/debt'
      path: '/debt'
      fullPath: '/debt'
      preLoaderRoute: typeof AppDebtRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/music': {
      id: '/_app/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof AppMusicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uploads': {
      id: '/_app/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof AppUploadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtRoute: typeof AppDebtRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppMembersRoute: typeof AppMembersRoute
  AppMusicRoute: typeof AppMusicRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppUploadsRoute: typeof AppUploadsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtRoute: AppDebtRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppMembersRoute: AppMembersRoute,
  AppMusicRoute: AppMusicRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatisticsRoute: AppStatisticsRoute,
  AppUploadsRoute: AppUploadsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
  SelectSectionRoute: SelectSectionRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
