# Generated by Django 5.2.16 on 2026-07-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('composer', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('HYMN', 'Hymn'), ('ANTHEM', 'Anthem'), ('CONTEMPORARY', 'Contemporary'), ('CLASSICAL', 'Classical'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='music/pdf/')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='music/docx/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music/audio/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Music Library',
            },
        ),
    ]
